# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Nylo Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  google_fonts: ^8.1.0
  analyzer: ^10.0.1
  intl: ^0.20.2
  nylo_framework: ^7.1.18
  cupertino_icons: ^1.0.9
  font_awesome_flutter: ^11.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  # The following line 'flutter_lints' activates a set of recommended lints.
#  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/icon.png"
  remove_alpha_ios: true

flutter:


  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/app_icon/
    - lang/
