import 'package:nylo_framework/networking/base_networking.dart';
import 'package:http/http.dart';

/// This file can be auto generated by running the following:
///
/// 'flutter pub run nylo_framework:main apispec:build'
///
/// ! Important !
/// Running apispec:build will overwrite any changes in this file.
/// To learn more about the API spec, check out our documentation here
/// https://nylo.dev/docs/1.x/metro#what-is-an-apispec
class ApiService extends BaseApi {
  
  var _client;

  ApiService() : _client = new Client();
  
  
  
}
